config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
     @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end
    
    def create
        @post = Post.create(post_params)
        @post.user_id = current_user.id
        @post.save
    end 

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
        end
    end


    def destroy
        @post = Post.find_by(params[:id])
        if @post.destroy
        end
    end
  

    private 

    def post_params
        params.require(:post).permit(:name, :description, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>Portfolio</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      
      <%# Here Go The Navbar %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
        </div>
      </nav>
      

    <%# <%= render 'shared/navbar' %> 
    <%# <%= render 'shared/flashes' %> 
    <% if notice %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
  _        _    ____   ____ _____   ___ _   _ _____ ____   ___    ____  _____ ____ _____ ___ ___  _   _ 
      | |      / \  |  _ \ / ___| ____| |_ _| \ | |_   _|  _ \ / _ \  / ___|| ____/ ___|_   _|_ _/ _ \| \ | |
      | |     / _ \ | |_) | |  _|  _|    | ||  \| | | | | |_) | | | | \___ \|  _|| |     | |  | | | | |  \| |
      | |___ / ___ \|  _ <| |_| | |___   | || |\  | | | |  _ <| |_| |  ___) | |__| |___  | |  | | |_| | |\  |
      |_____/_/   \_\_| \_\\____|_____| |___|_| \_| |_| |_| \_\\___/  |____/|_____\____| |_| |___\___/|_| \_|
          
  div.amen*6    
      <div class="about-me">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Dignissim enim sit amet venenatis urna. Non nisi est sit amet facilisis. Rutrum quisque non tellus orci ac. 
        Tempus egestas sed sed risus pretium quam vulputate. Mi in nulla posuere sollicitudin aliquam ultrices. 
        Lacus laoreet non curabitur gravida arcu ac tortor dignissim. Enim tortor at auctor urna nunc id. 
        Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Ac auctor augue mauris augue neque. Libero volutpat sed cras ornare. 
        Ut lectus arcu bibendum at varius. Mi quis hendrerit dolor magna eget est. Ac turpis egestas sed tempus urna. 
        Auctor elit sed vulputate mi sit amet mauris commodo quis. Sit amet porttitor eget dolor morbi non arcu risus quis.
        Diam vulputate ut pharetra sit amet aliquam. Bibendum neque egestas congue quisque egestas diam.
        Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. 
        Iaculis at erat pellentesque adipiscing. Turpis in eu mi bibendum neque egestas. Porttitor leo a diam sollicitudin tempor id.
        Congue quisque egestas diam in arcu. Vulputate enim nulla aliquet porttitor lacus luctus. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. 
        Malesuada bibendum arcu vitae elementum curabitur vitae nunc. Sit amet consectetur adipiscing elit ut aliquam purus sit. 
        In aliquam sem fringilla ut morbi tincidunt augue. Eu mi bibendum neque egestas congue quisque egestas diam. Ac turpis egestas integer eget aliquet nibh praesent.
        Integer eget aliquet nibh praesent tristique magna. Eget nullam non nisi est sit amet facilisis. Interdum posuere lorem ipsum dolor sit amet.
      </div>

app/views/posts/index.html.erb
<%  @posts.each do |post|%>
    <h1><%= post.name %></h1>
    <p><%= post.description %></p>
    <%= link_to "See post", post_path(post) %>
    <%= link_to "update post", post_path(post), method: :patch %>
    <%= link_to "Delete  post", post_path(post), method: :delete %>
    <p>--------------------------------------</p>
<% end %>

<%= link_to "Create New Post", new_post_path %>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
    <%= f.input :name, label: "name" %>
    <%= f.input :description, label: "description" %>
    <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.name %></h1>
<p><%= @post.description%></p>
<%= link_to "Back to Main Page", posts_path  %>

app/views/posts/update.html.erb
<%= simple_form_for @post do |f| %>
    <%= f.input :name, label: "name" %>
    <%= f.input :description, label: "description" %>
    <%= f.submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>